name: Bug report
description: Report un bug
title: '[Bug]: '
labels:
  - bug
assignees:
  - AlphaII
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo Discord
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Dites-nous ce qui est arrivé
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
