name: Signaler un bug
description: Signaler une erreur ou une réponse innatendue de la poart du bot
title: '[Bug]: '
labels:
  - Bug
assignees:
  - AlphaII
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description du problème'
      description: Décrivez le problème de la façon la plus détaillée possible. Merci de veiller à ce que cette desciption soit claire, concise et complète
      placeholder: "1. Aller dans le salon #salon ; 2. Faire la commande /command ; 3. ..."
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Système d'exploitation"
      description: "Sur quel(s) système(s) d'exploitation rencontrez-vous ce problème ?"
      options:
        - Windows
        - Android
        - Linux
        - macOS
        - iOS
        - Autre
  - type: checkboxes
    id: web
    attributes:
      label: Version web de Discord
      description: Cochez cette case si vous utilisez Discord sur votre navigateur
      options:
        - label: J'utilise la version web de Discord
