name: Bug report
description: Signaler un bug
title: '[Bug]: '
labels:
  - Bug
assignees:
  - AlphaII
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description du problème'
      description: Décrivez le problème de la façon la plus détaillée possible
      placeholder: "1. Aller dans le salon #salon 2. Faire la commande /command  3. ..."
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Système d'exploitation"
      description: "Sur quel(s) système(s) d'exploitation rencontrez-vous ce problème ?"
      options:
        - Windows
        - Android
        - Linux
        - macOS
        - iOS
        - Autre
