name: Une question ?
description: Faites nous part de votre question
title: '[Question]: '
labels:
  - question
assignees:
  - AlphaII
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo Discord
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Votre question
      description: Quelle est votre question ?
    validations:
      required: true
