name: Une question ?
description: Faites nous part de votre question
title: '[Question]: '
labels:
  - Question
assignees:
  - AlphaII
body:
  - type: textarea
    id: question
    attributes:
      label: Votre question
      description: Quelle est votre question ?
    validations:
      required: true
